import type { Metadata } from "next";

import { auth } from "../../auth";
import { SessionProvider } from "next-auth/react";

import { nunito } from "@/utils/fonts";

export const metadata: Metadata = {
  title: "Librería Goto - Tienda",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <h2>hola</h2>
      <section className="flex justify-center items-center min-h-lvh">
        {children}
      </section>
    </>
  );
}
