import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "CAndyCortantes - Tienda",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <h2>hola</h2>
      <section className="flex justify-center items-center min-h-lvh">
        {children}
      </section>
    </>
  );
}
